dir: '{{.InterfaceDirRelative}}'
template: testify
template-data:
  mock-build-tags: '!release'
  unroll-variadic: true
packages:
  log/slog:
    interfaces:
      Handler:
        config:
          dir: internal/diag
          structname: MockSlogHandler
          pkgname: diag
  github.com/gemyago/golang-backend-boilerplate/internal/app:
    interfaces:
      UsersRepository:
        config:
          dir: internal/app
          structname: MockUsersRepository
          pkgname: app
