// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package app

import (
	"context"

	"github.com/gemyago/golang-backend-boilerplate/internal/infrastructure/petstore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPetsRepository creates a new instance of MockPetsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetsRepository {
	mock := &MockPetsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetsRepository is an autogenerated mock type for the PetsRepository type
type MockPetsRepository struct {
	mock.Mock
}

type MockPetsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetsRepository) EXPECT() *MockPetsRepository_Expecter {
	return &MockPetsRepository_Expecter{mock: &_m.Mock}
}

// AddUserPet provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) AddUserPet(ctx context.Context, userPet UserPet) error {
	ret := _mock.Called(ctx, userPet)

	if len(ret) == 0 {
		panic("no return value specified for AddUserPet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UserPet) error); ok {
		r0 = returnFunc(ctx, userPet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPetsRepository_AddUserPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserPet'
type MockPetsRepository_AddUserPet_Call struct {
	*mock.Call
}

// AddUserPet is a helper method to define mock.On call
//   - ctx context.Context
//   - userPet UserPet
func (_e *MockPetsRepository_Expecter) AddUserPet(ctx interface{}, userPet interface{}) *MockPetsRepository_AddUserPet_Call {
	return &MockPetsRepository_AddUserPet_Call{Call: _e.mock.On("AddUserPet", ctx, userPet)}
}

func (_c *MockPetsRepository_AddUserPet_Call) Run(run func(ctx context.Context, userPet UserPet)) *MockPetsRepository_AddUserPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UserPet
		if args[1] != nil {
			arg1 = args[1].(UserPet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetsRepository_AddUserPet_Call) Return(err error) *MockPetsRepository_AddUserPet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPetsRepository_AddUserPet_Call) RunAndReturn(run func(ctx context.Context, userPet UserPet) error) *MockPetsRepository_AddUserPet_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPetIDs provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) GetUserPetIDs(ctx context.Context, userID string) ([]int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPetIDs")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetsRepository_GetUserPetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPetIDs'
type MockPetsRepository_GetUserPetIDs_Call struct {
	*mock.Call
}

// GetUserPetIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPetsRepository_Expecter) GetUserPetIDs(ctx interface{}, userID interface{}) *MockPetsRepository_GetUserPetIDs_Call {
	return &MockPetsRepository_GetUserPetIDs_Call{Call: _e.mock.On("GetUserPetIDs", ctx, userID)}
}

func (_c *MockPetsRepository_GetUserPetIDs_Call) Run(run func(ctx context.Context, userID string)) *MockPetsRepository_GetUserPetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetsRepository_GetUserPetIDs_Call) Return(int64s []int64, err error) *MockPetsRepository_GetUserPetIDs_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockPetsRepository_GetUserPetIDs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]int64, error)) *MockPetsRepository_GetUserPetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// HasUserPet provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) HasUserPet(ctx context.Context, userID string, petID int64) (bool, error) {
	ret := _mock.Called(ctx, userID, petID)

	if len(ret) == 0 {
		panic("no return value specified for HasUserPet")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (bool, error)); ok {
		return returnFunc(ctx, userID, petID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) bool); ok {
		r0 = returnFunc(ctx, userID, petID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, userID, petID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetsRepository_HasUserPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUserPet'
type MockPetsRepository_HasUserPet_Call struct {
	*mock.Call
}

// HasUserPet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - petID int64
func (_e *MockPetsRepository_Expecter) HasUserPet(ctx interface{}, userID interface{}, petID interface{}) *MockPetsRepository_HasUserPet_Call {
	return &MockPetsRepository_HasUserPet_Call{Call: _e.mock.On("HasUserPet", ctx, userID, petID)}
}

func (_c *MockPetsRepository_HasUserPet_Call) Run(run func(ctx context.Context, userID string, petID int64)) *MockPetsRepository_HasUserPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPetsRepository_HasUserPet_Call) Return(b bool, err error) *MockPetsRepository_HasUserPet_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPetsRepository_HasUserPet_Call) RunAndReturn(run func(ctx context.Context, userID string, petID int64) (bool, error)) *MockPetsRepository_HasUserPet_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserPet provides a mock function for the type MockPetsRepository
func (_mock *MockPetsRepository) RemoveUserPet(ctx context.Context, userID string, petID int64) error {
	ret := _mock.Called(ctx, userID, petID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserPet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, userID, petID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPetsRepository_RemoveUserPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserPet'
type MockPetsRepository_RemoveUserPet_Call struct {
	*mock.Call
}

// RemoveUserPet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - petID int64
func (_e *MockPetsRepository_Expecter) RemoveUserPet(ctx interface{}, userID interface{}, petID interface{}) *MockPetsRepository_RemoveUserPet_Call {
	return &MockPetsRepository_RemoveUserPet_Call{Call: _e.mock.On("RemoveUserPet", ctx, userID, petID)}
}

func (_c *MockPetsRepository_RemoveUserPet_Call) Run(run func(ctx context.Context, userID string, petID int64)) *MockPetsRepository_RemoveUserPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPetsRepository_RemoveUserPet_Call) Return(err error) *MockPetsRepository_RemoveUserPet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPetsRepository_RemoveUserPet_Call) RunAndReturn(run func(ctx context.Context, userID string, petID int64) error) *MockPetsRepository_RemoveUserPet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPetstoreClient creates a new instance of MockPetstoreClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetstoreClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetstoreClient {
	mock := &MockPetstoreClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPetstoreClient is an autogenerated mock type for the PetstoreClient type
type MockPetstoreClient struct {
	mock.Mock
}

type MockPetstoreClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetstoreClient) EXPECT() *MockPetstoreClient_Expecter {
	return &MockPetstoreClient_Expecter{mock: &_m.Mock}
}

// AddPet provides a mock function for the type MockPetstoreClient
func (_mock *MockPetstoreClient) AddPet(ctx context.Context, params petstore.AddPetParams) (*petstore.Pet, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for AddPet")
	}

	var r0 *petstore.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.AddPetParams) (*petstore.Pet, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.AddPetParams) *petstore.Pet); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*petstore.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, petstore.AddPetParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetstoreClient_AddPet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPet'
type MockPetstoreClient_AddPet_Call struct {
	*mock.Call
}

// AddPet is a helper method to define mock.On call
//   - ctx context.Context
//   - params petstore.AddPetParams
func (_e *MockPetstoreClient_Expecter) AddPet(ctx interface{}, params interface{}) *MockPetstoreClient_AddPet_Call {
	return &MockPetstoreClient_AddPet_Call{Call: _e.mock.On("AddPet", ctx, params)}
}

func (_c *MockPetstoreClient_AddPet_Call) Run(run func(ctx context.Context, params petstore.AddPetParams)) *MockPetstoreClient_AddPet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 petstore.AddPetParams
		if args[1] != nil {
			arg1 = args[1].(petstore.AddPetParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetstoreClient_AddPet_Call) Return(pet *petstore.Pet, err error) *MockPetstoreClient_AddPet_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetstoreClient_AddPet_Call) RunAndReturn(run func(ctx context.Context, params petstore.AddPetParams) (*petstore.Pet, error)) *MockPetstoreClient_AddPet_Call {
	_c.Call.Return(run)
	return _c
}

// GetPetByID provides a mock function for the type MockPetstoreClient
func (_mock *MockPetstoreClient) GetPetByID(ctx context.Context, params petstore.GetPetByIDParams) (*petstore.Pet, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPetByID")
	}

	var r0 *petstore.Pet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.GetPetByIDParams) (*petstore.Pet, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, petstore.GetPetByIDParams) *petstore.Pet); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*petstore.Pet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, petstore.GetPetByIDParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPetstoreClient_GetPetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPetByID'
type MockPetstoreClient_GetPetByID_Call struct {
	*mock.Call
}

// GetPetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - params petstore.GetPetByIDParams
func (_e *MockPetstoreClient_Expecter) GetPetByID(ctx interface{}, params interface{}) *MockPetstoreClient_GetPetByID_Call {
	return &MockPetstoreClient_GetPetByID_Call{Call: _e.mock.On("GetPetByID", ctx, params)}
}

func (_c *MockPetstoreClient_GetPetByID_Call) Run(run func(ctx context.Context, params petstore.GetPetByIDParams)) *MockPetstoreClient_GetPetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 petstore.GetPetByIDParams
		if args[1] != nil {
			arg1 = args[1].(petstore.GetPetByIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPetstoreClient_GetPetByID_Call) Return(pet *petstore.Pet, err error) *MockPetstoreClient_GetPetByID_Call {
	_c.Call.Return(pet, err)
	return _c
}

func (_c *MockPetstoreClient_GetPetByID_Call) RunAndReturn(run func(ctx context.Context, params petstore.GetPetByIDParams) (*petstore.Pet, error)) *MockPetstoreClient_GetPetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) CreateUser(ctx context.Context, user User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
func (_e *MockUsersRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUsersRepository_CreateUser_Call {
	return &MockUsersRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUsersRepository_CreateUser_Call) Run(run func(ctx context.Context, user User)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) Return(err error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user User) error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUsersRepository_Expecter) DeleteUser(ctx interface{}, userID interface{}) *MockUsersRepository_DeleteUser_Call {
	return &MockUsersRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockUsersRepository_DeleteUser_Call) Run(run func(ctx context.Context, userID string)) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) Return(err error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUsersRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsersRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUsersRepository_GetUserByEmail_Call {
	return &MockUsersRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Return(user *User, err error) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*User, error)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByID(ctx context.Context, userID string) (*User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUsersRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUsersRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUsersRepository_GetUserByID_Call {
	return &MockUsersRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUsersRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByID_Call) Return(user *User, err error) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*User, error)) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) ListUsers(ctx context.Context) ([]*User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUsersRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersRepository_Expecter) ListUsers(ctx interface{}) *MockUsersRepository_ListUsers_Call {
	return &MockUsersRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockUsersRepository_ListUsers_Call) Run(run func(ctx context.Context)) *MockUsersRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUsersRepository_ListUsers_Call) Return(users []*User, err error) *MockUsersRepository_ListUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersRepository_ListUsers_Call) RunAndReturn(run func(ctx context.Context) ([]*User, error)) *MockUsersRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) UpdateUser(ctx context.Context, user User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsersRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
func (_e *MockUsersRepository_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockUsersRepository_UpdateUser_Call {
	return &MockUsersRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockUsersRepository_UpdateUser_Call) Run(run func(ctx context.Context, user User)) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_UpdateUser_Call) Return(err error) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user User) error) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
