// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"encoding/json"
	"fmt"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type _ func() EchoRequestPayload

// EchoSendEchoRequest represents params for sendEcho operation
//
// Request: POST /echo.
type EchoSendEchoRequest struct {
	// Payload is parsed from request body and declared as payload.
	Payload *EchoRequestPayload
}

type EchoController struct {
	// POST /echo
	//
	// Request type: EchoSendEchoRequest,
	//
	// Response type: EchoResponsePayload
	SendEcho httpHandlerFactory
}

type EchoControllerBuilder struct {
	// POST /echo
	//
	// Request type: EchoSendEchoRequest,
	//
	// Response type: EchoResponsePayload
	HandleSendEcho actionBuilder[*EchoControllerBuilder, *EchoSendEchoRequest, *EchoResponsePayload]
}

func (c *EchoControllerBuilder) Finalize() *EchoController {
	return &EchoController{
		SendEcho: mustInitializeAction("sendEcho", c.HandleSendEcho.httpHandlerFactory),
	}
}

func BuildEchoController() *EchoControllerBuilder {
	controllerBuilder := &EchoControllerBuilder{}

	// POST /echo
	controllerBuilder.HandleSendEcho.controllerBuilder = controllerBuilder
	controllerBuilder.HandleSendEcho.defaultStatusCode = 200
	controllerBuilder.HandleSendEcho.paramsParserFactory = newParamsParserEchoSendEcho

	return controllerBuilder
}

func RegisterEchoRoutes(controller *EchoController, app *HTTPApp) {
	app.router.HandleRoute("POST", "/echo", controller.SendEcho(app))
}
