// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"encoding/json"
	"fmt"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type _ func() Error



type HealthController struct {
	// GET /health
	//
	// Request type: none
	//
	// Response type: none
	HealthCheck httpHandlerFactory
}

type HealthControllerBuilder struct {
	// GET /health
	//
	// Request type: none
	//
	// Response type: none
	HandleHealthCheck actionBuilderNoParamsVoidResult[*HealthControllerBuilder]
}

func (c *HealthControllerBuilder) Finalize() *HealthController {
	return &HealthController{
		HealthCheck: mustInitializeAction("healthCheck", c.HandleHealthCheck.httpHandlerFactory),
	}
}

func BuildHealthController() *HealthControllerBuilder {
	controllerBuilder := &HealthControllerBuilder{}

	// GET /health
	controllerBuilder.HandleHealthCheck.controllerBuilder = controllerBuilder
	controllerBuilder.HandleHealthCheck.defaultStatusCode = 204
	controllerBuilder.HandleHealthCheck.voidResult = true
	controllerBuilder.HandleHealthCheck.paramsParserFactory = makeVoidParamsParser

	return controllerBuilder
}

func RegisterHealthRoutes(controller *HealthController, app *HTTPApp) {
	app.router.HandleRoute("GET", "/health", controller.HealthCheck(app))
}
