// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports.
var _ = time.Time{}
type _ func() Error


