// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	. "github.com/gemyago/golang-backend-boilerplate/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = http.MethodGet
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type _ func() Error



type healthControllerBuilder struct {
	// GET /health
	//
	// Request type: none
	//
	// Response type: none
	HealthCheck genericHandlerBuilder[
		void,
		void,
		handlerActionFuncNoParamsNoResponse[void, void],
		httpHandlerActionFuncNoParamsNoResponse[void, void],
	]
}

func newHealthControllerBuilder(app *RootHandler) *healthControllerBuilder {
	return &healthControllerBuilder{
		// GET /health
		HealthCheck: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoParamsNoResponse[
				void,
				void,
			](),
			newHTTPHandlerAdapterNoParamsNoResponse[
				void,
				void,
			](),
			makeActionBuilderParams[
				void,
				void,
			]{
				defaultStatus: 204,
				voidResult:    true,
				paramsParser:  makeVoidParamsParser(app),
			},
		),
	}
}

type HealthController interface {
	// GET /health
	//
	// Request type: none
	//
	// Response type: none
	HealthCheck(NoParamsNoResponseHandlerBuilder) http.Handler
}

// RegisterHealthRoutes will attach the following routes to the root handler:
// 
// - GET /health
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterHealthRoutes(controller HealthController) *RootHandler {
	builder := newHealthControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("GET", "/health", controller.HealthCheck(builder.HealthCheck))
	return rootHandler
}