name: Promote Docker Images

on:
  pull_request:
    # types: [closed]
    types: [labeled] # Use this for testing (comment out the merged condition)

jobs:
  promote:
    name: Promote Images
    # if: github.event.pull_request.merged == true # For testing, comment out the merged condition
    runs-on: ubuntu-24.04
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup deps
        working-directory: build
        run: |
          make install-crane

      - name: Download docker artifacts
        working-directory: build
        run: |
          gh run download --repo ${{ github.repository }} \
            --name docker-artifacts-pr-${{ github.event.pull_request.node_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract docker artifacts
        working-directory: build
        run: |
          if [[ ! -f docker-artifacts.tar.bz2 ]]; then
            echo "Error: docker-artifacts.tar.bz2 not found in downloaded artifact."
            exit 1
          fi
          tar -xf docker-artifacts.tar.bz2
          # Ensure the .remote-images file exists after extraction
          if [[ ! -f docker/.remote-images ]]; then
            echo "Error: build/docker/.remote-images not found after extracting artifact."
            ls -la # List files for debugging
            exit 1
          fi

      - name: Tag and Promote Docker Images
        run: |
          git_head_sha=$(cat build/.git-meta/HEAD)
          merge_commit_sha="${{ github.event.pull_request.merge_commit_sha }}"
          if [[ -n "$merge_commit_sha" ]]; then
            target_commit_sha="$merge_commit_sha"
          else
            target_commit_sha="$git_head_sha"
          fi
          build/scripts/tag-remote-images.sh \
            --remote-images-file build/docker/.remote-images \
            --source-commit-sha "${git_head_sha}" \
            --target-commit-sha "${target_commit_sha}" \
            --git-ref "refs/heads/${{ github.event.pull_request.base.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}